<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GuruSeeder extends Seeder
{
    public function run(): void
    {
        $json = <<<'JSON'
[
    {
        "no": "1",
        "nama": "ERNA WIDAYANTI, S.Pd.SD",
        "nip": "19770123 201406 2 001",
        "karpeg": "B. 01019174",
        "nuptk": "1455755656210062",
        "gender": "P",
        "jabatan": "Kepala Sekolah",
        "tempat_tgl_lahir": "Jer, 23/01/1977",
        "ijazah": "S1 10",
        "mulai_bekerja_permulaan": "01/06/2014",
        "mulai_bekerja_di_sini": "21/05/2024",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "III/B",
        "tmt": "",
        "gaji_pokok": "#########",
        "gr_kls_mp": "",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "",
        "sertifikasi_tahun": "2016",
        "sertifikasi_nrg": ""
    },
    {
        "no": "2",
        "nama": "Hastiningsih, S.Pd.SD",
        "nip": "19660508 199103 2 009",
        "karpeg": "E. 946219",
        "nuptk": "68407464 4621 0082",
        "gender": "P",
        "jabatan": "Gr.Kelas",
        "tempat_tgl_lahir": "Jpr, 08/05/1966",
        "ijazah": "S-I 09",
        "mulai_bekerja_permulaan": "03/01/1991",
        "mulai_bekerja_di_sini": "03/01/1991",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "IV/A",
        "tmt": "04/01/2012",
        "gaji_pokok": "4.603.500",
        "gr_kls_mp": "Gr.KLS I",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "13032002711349",
        "sertifikasi_tahun": "2013",
        "sertifikasi_nrg": "'132201541006"
    },
    {
        "no": "3",
        "nama": "DEWI SUHARTUTI,S.Pd.SD",
        "nip": "19690115 200701 2 017",
        "karpeg": "N.119564",
        "nuptk": "1447747 649210092",
        "gender": "P",
        "jabatan": "Gr.Kelas",
        "tempat_tgl_lahir": "Jpr 17/12/1966",
        "ijazah": "S-I 11",
        "mulai_bekerja_permulaan": "01/01/1989",
        "mulai_bekerja_di_sini": "01/01/2007",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "III/B",
        "tmt": "04/01/2012",
        "gaji_pokok": "3.238.000",
        "gr_kls_mp": "Gr.Kl.VI",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "13032002711074",
        "sertifikasi_tahun": "2013",
        "sertifikasi_nrg": "130217777130"
    },
    {
        "no": "4",
        "nama": "MAIUN ISROILYANA S.Pd.SD",
        "nip": "19780712 201001 2 018",
        "karpeg": "P.672298",
        "nuptk": "80447546  58210123",
        "gender": "P",
        "jabatan": "Gr.Kelas",
        "tempat_tgl_lahir": "Jpr, 08/05/1978",
        "ijazah": "S-I 10",
        "mulai_bekerja_permulaan": "05/01/2010",
        "mulai_bekerja_di_sini": "05/01/2010",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "III/B",
        "tmt": "10/01/2017",
        "gaji_pokok": "3.012.000",
        "gr_kls_mp": "Gr.Kl.IV",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "",
        "sertifikasi_tahun": "2014",
        "sertifikasi_nrg": ""
    },
    {
        "no": "5",
        "nama": "SUPRIYANAH S.Pd.SD",
        "nip": "19720108 201406 2 001",
        "karpeg": "B. 0101946",
        "nuptk": "4440750 6651210042",
        "gender": "P",
        "jabatan": "Guru Kelas",
        "tempat_tgl_lahir": "Jpr, 12/07/1972",
        "ijazah": "S-I 10",
        "mulai_bekerja_permulaan": "08/01/2003",
        "mulai_bekerja_di_sini": "08/01/2003",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "III/B",
        "tmt": "10/01/2017",
        "gaji_pokok": "3.012.000",
        "gr_kls_mp": "Gr.Kl.V",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "",
        "sertifikasi_tahun": "2015",
        "sertifikasi_nrg": ""
    },
    {
        "no": "6",
        "nama": "TRI AJI WIJAYANTO, S.Pd.SD",
        "nip": "19840510 201406 1 002",
        "karpeg": "B. 0101940",
        "nuptk": "5842 7626 64110072",
        "gender": "L",
        "jabatan": "Guru Kelas",
        "tempat_tgl_lahir": "Jpr, 08/05/1984",
        "ijazah": "S-I 10",
        "mulai_bekerja_permulaan": "01/02/2003",
        "mulai_bekerja_di_sini": "20/01/2015",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "III/B",
        "tmt": "06/01/2014",
        "gaji_pokok": "2.012.000",
        "gr_kls_mp": "Gr.Kl.II",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "",
        "sertifikasi_tahun": "2016",
        "sertifikasi_nrg": ""
    },
    {
        "no": "7",
        "nama": "WIDHA AGUSTINA , S.I. Pust, S.Pd",
        "nip": "198408222024212016",
        "karpeg": "",
        "nuptk": "41547612663131103",
        "gender": "P",
        "jabatan": "Guru Kelas",
        "tempat_tgl_lahir": "Jpr, 22/08/1984",
        "ijazah": "DII 13",
        "mulai_bekerja_permulaan": "02/01/2010",
        "mulai_bekerja_di_sini": "02/01/2010",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "IX",
        "tmt": "01/02/2010",
        "gaji_pokok": "`",
        "gr_kls_mp": "Gr. Kls III",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "",
        "sertifikasi_tahun": "",
        "sertifikasi_nrg": ""
    },
    {
        "no": "8",
        "nama": "ASTIKA ARFIANA, S.Pd",
        "nip": "199006032025212083",
        "karpeg": "-",
        "nuptk": "",
        "gender": "P",
        "jabatan": "Guru Mapel",
        "tempat_tgl_lahir": "Jpr, 03 Juni 1990",
        "ijazah": "S1 2015",
        "mulai_bekerja_permulaan": "01/06/2020",
        "mulai_bekerja_di_sini": "01/06/2020",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "",
        "tmt": "",
        "gaji_pokok": "",
        "gr_kls_mp": "G. B Ingg",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "",
        "sertifikasi_tahun": "",
        "sertifikasi_nrg": ""
    },
    {
        "no": "9",
        "nama": "IDA ROHYANI",
        "nip": "198709042003212017",
        "karpeg": "-",
        "nuptk": "5236765666230213",
        "gender": "P",
        "jabatan": "Guru Mapel",
        "tempat_tgl_lahir": "Jpr,  4/11/1987",
        "ijazah": "S1 2015",
        "mulai_bekerja_permulaan": "06/01/2016",
        "mulai_bekerja_di_sini": "09/01/2018",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "IX",
        "tmt": "",
        "gaji_pokok": "",
        "gr_kls_mp": "GPAI",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "",
        "sertifikasi_tahun": "",
        "sertifikasi_nrg": ""
    },
    {
        "no": "10",
        "nama": "EMUT SUBEKTI NINGSIH, S.Pd",
        "nip": "198911042025212087",
        "karpeg": "",
        "nuptk": "",
        "gender": "",
        "jabatan": "Pustakawan",
        "tempat_tgl_lahir": "Jpr, 4/11/1989",
        "ijazah": "S1 2022",
        "mulai_bekerja_permulaan": "01/08/2020",
        "mulai_bekerja_di_sini": "01/08/2020",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "",
        "tmt": "",
        "gaji_pokok": "",
        "gr_kls_mp": "Pustakawan",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "",
        "sertifikasi_tahun": "",
        "sertifikasi_nrg": ""
    },
    {
        "no": "11",
        "nama": "Muhammad Sunarwie",
        "nip": "198204102025211142",
        "karpeg": "-",
        "nuptk": "",
        "gender": "L",
        "jabatan": "PENJAGA",
        "tempat_tgl_lahir": "Jepara,12/02/1982",
        "ijazah": "SMP",
        "mulai_bekerja_permulaan": "01/12/2020",
        "mulai_bekerja_di_sini": "01/12/2020",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "",
        "tmt": "01/12/2020",
        "gaji_pokok": "",
        "gr_kls_mp": "Penjaga",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "",
        "sertifikasi_tahun": "",
        "sertifikasi_nrg": ""
    },
    {
        "no": "12",
        "nama": "Taufik Dwi Prasetyo",
        "nip": "199103202025211111",
        "karpeg": "",
        "nuptk": "",
        "gender": "L",
        "jabatan": "Oprator",
        "tempat_tgl_lahir": "Jep, 20/03/1991",
        "ijazah": "S1 2022",
        "mulai_bekerja_permulaan": "20/07/2020",
        "mulai_bekerja_di_sini": "20/07/2020",
        "masa_kerja_th": "",
        "masa_kerja_bl": "",
        "gol": "",
        "tmt": "20/07/2020",
        "gaji_pokok": "",
        "gr_kls_mp": "Oprator",
        "absen_s": "",
        "absen_i": "",
        "absen_a": "",
        "sk_akhir_tanggal": "",
        "sertifikasi_nmr_psrt": "",
        "sertifikasi_tahun": "",
        "sertifikasi_nrg": ""
    }
]
JSON;

        $rows = collect(json_decode($json, true))
            ->map(function (array $row) {
                $clean = [];
                foreach ($row as $key => $value) {
                    $value = is_string($value) ? trim($value) : $value;
                    if ($value === '' || $value === '-') {
                        $value = null;
                    }
                    $clean[$key] = $value;
                }

                $clean['no'] = (int) $clean['no'];
                $clean['created_at'] = now();
                $clean['updated_at'] = now();

                return $clean;
            })
            ->all();

        DB::table('gurus')->insert($rows);
    }
}
